### ISSUE TITLE
Desbloqueio de senha em lote 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#322]
Ao tentar carregar o arquivo de desbloqueio de senha
![cpf lote](https://cloud.githubusercontent.com/assets/12251958/15076750/86c4592a-1381-11e6-9a43-52c79adf5623.JPG)
 em lote está apresentando a mensagem de erro anexo.

**Comment by wagnerlopes** [comment]
Ontem ao fazer manutenção no servidor apaguei sem querer o diretório
/var/tmp o que ocasionou o erro.
Quando ocorrer problemas desse tipo fale com o Cap Romulo que ele acerta o
servidor.
Em 06/05/2016 11:56 AM, "Ten Sampaio" <notifications@github.com> escreveu:

Ao tentar carregar o arquivo de desbloqueio de senha
[image: cpf lote]
<https://cloud.githubusercontent.com/assets/12251958/15076750/86c4592a-1381-11e6-9a43-52c79adf5623.JPG>
em lote está apresentando a mensagem de erro anexo.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/SERMIL/portal/issues/322>
