### ISSUE TITLE
Agendamento de CS Volante

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#340]
Caro Cel @wagnerlopes 

Um usuario me trouxe uma duvida bastante coerente.
Ele cadastrou uma CS volante que vai funcionar em tres localidades diferentes: A, B e C

Como ele pode ter certeza de que os cidadaos da localidade A serao agendados para a CS A, e os cidadaos de B para a CS B e assim por diante? 

Inicialmente nao dei nenhuma resposta para falar com o sr primeiro.

@fabiosampaio12

**Comment by wagnerlopes** [comment]
Sendo de localidades diferentes, são de juntas diferentes, então cada
universo está separado um do outro pelo código CSM/JSM e pelo código de
município.
Eu tenho código município do endereço que cadastrou para A, B, c, então vou
tentar colocar o povo do município do endereço A naquele período.
Já viu que este código vai ser difícil.
Em 01/06/2016 3:07 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

Caro Cel @wagnerlopes <https://github.com/wagnerlopes>

Um usuario me trouxe uma duvida bastante coerente.
Ele cadastrou uma CS volante que vai funcionar em tres localidades
diferentes: A, B e C

Como ele pode ter certeza de que os cidadaos da localidade A serao
agendados para a CS A, e os cidadaos de B para a CS B e assim por diante?

Inicialmente nao dei nenhuma resposta para falar com o sr primeiro.

@fabiosampaio12 <https://github.com/fabiosampaio12>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SERMIL/portal/issues/340>, or mute the thread
<https://github.com/notifications/unsubscribe/ABs4LwoOwl4zk0-7zSW4MMn0thBKxpr1ks5qHcp6gaJpZM4Ir0rO>
.

**Comment by 6975usa** [comment]
Obrigado pela resposta.
