### ISSUE TITLE
Auditoria de Perfis

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#348]
Nessa última versão do SERMIL, a auditoria de perfis não está mais disponível para usuários como Delegado de Serviço Militar, RM e outros, impossibilitando esses  auditarem e verificarem os usuários subordinados, inclusive comprometendo o trabalho devido a impossibilidade de verificação dos operadores cadastrados.

**Comment by wagnerlopes** [comment]
A ideia era limitar mesmo o acesso ao máximo, depois da intrusão realizada
pelo usuário da 16 CSM, diga-se, indevida!
Na próxima versão libero o acesso, mas preciso saber ao certo quais os
níveis que devem acessar o recurso.
Não passe nível adm pra ninguém.
nível dsm só pra ssmi.
Em 14/06/2016 10:53 AM, "Ten Sampaio" <notifications@github.com> escreveu:

Nessa última versão do SERMIL, a auditoria de perfis não está mais
disponível para usuários como Delegado de Serviço Militar, RM e outros,
impossibilitando esses auditarem e verificarem os usuários subordinados,
inclusive comprometendo o trabalho devido a impossibilidade de verificação
dos operadores cadastrados.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SERMIL/portal/issues/348>, or mute the thread
<https://github.com/notifications/unsubscribe/ABs4LziVzYEFozXtKeDhxrEtRIz6Bz7iks5qLrJmgaJpZM4I1WJR>
.

**Comment by fabiosampaio12** [comment]
Níveis que deverão ter acesso a auditoria de perfis:

Nível 01 - Administrador   
Nível 02 - DSM   
Nível 03 - RM   
Nível 04 - CSM      
Nível 08 - CS   
Nível 10 - Del SM   

@wagnerlopes

**Comment by wagnerlopes** [comment]
Versão 5.4.2
