### ISSUE TITLE
Erro alistamento SERMIL 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#356]
Algumas JSM estão reclamando que não estão conseguindo salvar o alistamentos diretamente no portal SERMIL. Está apresentando as mensagens de erro que estão no anexo. 
![erro alistar](https://cloud.githubusercontent.com/assets/12251958/16280720/6c27adfc-3897-11e6-9e94-23793017ab54.JPG)
![erro alistar1](https://cloud.githubusercontent.com/assets/12251958/16280726/72c05718-3897-11e6-9af8-d9025886838c.JPG)

**Comment by wagnerlopes** [comment]
Esse é aquele erro ORA-12801 que aparece de forma intermitente.
Até onde consegui averiguar, é um problema interno do banco, segundo a
Oracle existe um patch a ser instalado no servidor Oracle 11 que resolve o
problema. Precisa acionar o suporte Oracle para ver se procede.
A única coisa que fiz foi atualizar o drive JDBC para a versão 11.2.0.4 a
mesma do banco.
Em 22/06/2016 4:38 PM, "Ten Sampaio" <notifications@github.com> escreveu:

Algumas JSM estão reclamando que não estão conseguindo salvar o
alistamentos diretamente no portal SERMIL. Está apresentando as mensagens
de erro que estão no anexo.
[image: erro alistar]
<https://cloud.githubusercontent.com/assets/12251958/16280720/6c27adfc-3897-11e6-9e94-23793017ab54.JPG>
[image: erro alistar1]
<https://cloud.githubusercontent.com/assets/12251958/16280726/72c05718-3897-11e6-9af8-d9025886838c.JPG>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SERMIL/portal/issues/356>, or mute the thread
<https://github.com/notifications/unsubscribe/ABs4Ly4DpdlzJNBOmtRhB8t-8HHcaD-Mks5qOY8wgaJpZM4I8JLb>
.

**Comment by wagnerlopes** [comment]
@romulodba 
Precisava tentar ver se há como aplicar os patch de segurança e atualização da oracle no servidor do EXADATA.
O erro 12801 está relacionado com um bug que ocorre no servidor ao inserir os parâmetros na consulta SQL. Não tem muito a fazer na aplicação, porque é um erro obscuro e intermitente, nem sempre ocorre e vai ficar assombrando o sistema eternamente.
Recebo sempre uma série de alertas da Oracle no e-mail sobre patch a serem instalados no servidor de banco de dados, mas duvido que o pessoal do suporte atualize o servidor, por medo ou desconhecimento. Sempre foi assim, desde a época que eu servi no C Infor 2, 3 CTA e no CDS.
Já tive muitas brigas em todos esses anos para fazer as coisas andarem nessa área de suporte.

**Comment by romulodba** [comment]
Beleza Cel vou providenciar a referida correção!


*Prof. Rômulo Santos*www. <http://www.dominandoti.com.br>do
<http://www.dominandoti.com.br>minandoti.com.br
<http://www.dominandoti.com.br>
*A melhor** p**reparação para concursos na área de tecnologia da
informação.*

Em 23 de junho de 2016 08:39, Wagner Lopes <notifications@github.com>
escreveu:
